name: Auto PR dev to main

on:
  schedule:
    - cron: '53 8 * * 1,2' # ë§¤ì£¼ ì›”ìš”ì¼(1)ê³¼ ìˆ˜ìš”ì¼(3) 9:00 ì‹œì— ì‹¤í–‰ë˜ë„ë¡ ìŠ¤ì¼€ì¤„ ì„¤ì • (Cron í‘œí˜„ì‹)

jobs:
  createPullRequest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        if: github.event_name == 'schedule'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          title: '[ì „ì²´] - ìë™ ë°°í¬ PR'
          body: 'ìë™ ìƒì„± PR dev -> main Merge'
          branch: dev
          base: main
          labels: |
            ğŸë°°
          reviewers: MinwooP, qkdl60, suehdn
